services:
    pg_tpl:
        image: postgres:17.2
        environment:
            POSTGRES_USER: ${SWD_PG_USER}
            POSTGRES_PASSWORD: ${SWD_PG_PASSWORD}
            POSTGRES_DB: ${SWD_PG_DBNAME}

    redis_tpl:
        image: redis/redis-stack:6.2.6-v18
        restart: always
        environment:
            - REDIS_ARGS=--requirepass ${SWD_REDIS_PASSWORD}

    cent_tpl:
        image: centrifugo/centrifugo:v6.0
        restart: always
        command: centrifugo -c config.json
        ulimits:
            nofile:
                soft: 65535
                hard: 65535

    pg_dev:
        extends:
            service: pg_tpl
        profiles:
            - dev
        container_name: swd_pg_dev
        restart: always
        volumes:
            - swd_pgdata:/var/lib/postgresql/data/
        ports:
            - "${SWD_PG_PORT}:5432"

    redis_dev:
        extends:
            service: redis_tpl
        profiles:
            - dev
        container_name: swd_redis_dev
#        command:
#            - /bin/sh
#            - -c
#            - redis-server --requirepass "$${SWD_REDIS_PASSWORD:?SWD_REDIS_PASSWORD variable is not set}"
        ports:
            - "${SWD_REDIS_PORT}:6379"

    cent_dev:
        extends:
            service: cent_tpl
        profiles:
            - dev
        container_name: swd_cent_dev
        volumes:
            - ./centrifugo.dev.json:/centrifugo/config.json
        ports:
            - "8105:8000"
networks:
    default:
        name: swd_network
        external: true

volumes:
    swd_pgdata:
