services:
    pg:
        container_name: swd_pg
        image: postgres:17.2
        restart: always
        volumes:
            - swd_pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: ${SWD_PG_USER}
            POSTGRES_PASSWORD: ${SWD_PG_PASSWORD}
            POSTGRES_DB: ${SWD_PG_DBNAME}
        ports:
            - "${SWD_PG_PORT}:5432"

    redis:
        container_name: swd_redis
        image: redis/redis-stack:6.2.6-v18
        restart: always
        volumes:
            - swd_rdsdata:/var/lib/postgresql/data/:/data
        environment:
            - REDIS_ARGS=--requirepass ${SWD_REDIS_PASSWORD}
        ports:
            - "${SWD_REDIS_PORT}:6379"

    cent:
        container_name: swd_cent
        image: centrifugo/centrifugo:v6.0
        restart: always
        volumes:
            - ./cent.prod.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - "10003:8000"
        ulimits:
            nofile:
                soft: 65535
                hard: 65535

    bot:
        container_name: swd_bot
        image: swd-bot
        ports:
            - "10007:10007"

networks:
    default:
        name: swd_network
        external: true

volumes:
    swd_pgdata:
    swd_rdsdata:
