services:
    pg:
        container_name: swd_pg
        image: postgres
        restart: always
        volumes:
            - swd_pgdata:/var/lib/postgresql/data/
        env_file:
            - .env.prod
        environment:
            POSTGRES_USER: ${SWD_PG_USER}
            POSTGRES_PASSWORD: ${SWD_PG_PASSWORD}
            POSTGRES_DB: ${SWD_PG_DBNAME}
        ports:
            - "${SWD_PG_PORT}:5432"

    redis:
        container_name: swd_redis
        image: redis
        restart: always
        volumes:
            - swd_rdsdata:/var/lib/postgresql/data/:/data
        env_file:
            - .env.prod
        command:
            - /bin/sh
            - -c
            - redis-server --requirepass "$${SWD_REDIS_PASSWORD:?SWD_REDIS_PASSWORD variable is not set}"
        ports:
            - "${SWD_REDIS_PORT}:6379"

    cent:
        container_name: swd_cent
        image: centrifugo/centrifugo:latest
        restart: always
        env_file:
            - .env.prod
        volumes:
            - ./cent.prod.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - "8105:8000"
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
networks:
    default:
        name: swd_network
        external: true

volumes:
    swd_pgdata:
    swd_rdsdata:
