version: '3.9'
services:
    pg_dev:
        container_name: swd_pg_dev
        image: postgres
        restart: always
        volumes:
            - swd_pgdata:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: ${SWD_PG_USER}
            POSTGRES_PASSWORD: ${SWD_PG_PASSWORD}
            POSTGRES_DB: ${SWD_PG_DBNAME}
        ports:
            - "${SWD_PG_PORT}:5432"

    redis_dev:
        container_name: swd_redis_dev
        image: redis
        restart: always
        ports:
            - "${SWD_REDIS_PORT}:6379"

    centrifugo:
        container_name: swd_cent_dev
        image: centrifugo/centrifugo:latest
        restart: always
        volumes:
            - ./centrifugo.dev.json:/centrifugo/config.json
        command: centrifugo -c config.json
        ports:
            - "8105:8000"
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
networks:
    default:
        name: swd_network
        external: true

volumes:
    swd_pgdata:
