CREATE TABLE "user"
(
    id         INT GENERATED BY DEFAULT AS IDENTITY,
    nickname   CITEXT                         NOT NULL,
    rating     SMALLINT                       NOT NULL,
    email      VARCHAR(255)                   NOT NULL,
    password   VARCHAR(255)                   NOT NULL,
    settings   JSONB                          NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX user_id_idx ON "user" (id);
CREATE UNIQUE INDEX user_email_idx ON "user" (email);
CREATE UNIQUE INDEX user_nickname_idx ON "user" (nickname);
-- add bot user
-- INSERT INTO public."user" (id, nickname, rating, email, password, settings, created_at) VALUES (2, 'bot', 1510, 'bot@7wd.io', '$2a$10$mLWeVbgbpiJVE3gTV3IvgOIe6WkEWsvBbqPEjnHyL66eX.pVImiHe', '{"game": {"animationSpeed": 3}, "sounds": {"myTurn": false, "opponentJoined": true}}', '2024-02-12 22:25:43');
